# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
      time: "12:00"
    assignees:
      - JoranAngevaare
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "ipykernel"
      - dependency-name: "ipython"
      - dependency-name: "ipython-genutils"
      - dependency-name: "jupyter"
      - dependency-name: "jupyter-console"
      - dependency-name: "jupyter-contrib-core"
      - dependency-name: "jupyter-contrib-nbextensions"
      - dependency-name: "jupyter-events"
      - dependency-name: "jupyter-highlight-selected-word"
      - dependency-name: "jupyter-nbextensions-configurator"
      - dependency-name: "jupyter-resource-usage"
      - dependency-name: "jupyter-server"
      - dependency-name: "jupyter_client"
      - dependency-name: "jupyter_core"
      - dependency-name: "jupyter_server_terminals"
      - dependency-name: "jupyterlab-pygments"
      - dependency-name: "jupyterlab-widgets"
      - dependency-name: "tornado"
    groups:
      fs-deps:
        patterns:
          - "gcsfs"
          - "fsspec"
      numba:
        patterns:
          - "numba"
          - "llvmlite"
      dask:
        patterns:
          - "dask"
          - "distributed"
      patches:
        update-types:
          - "patch"
