# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
      time: "12:00"
    # Raise all npm pull requests with an assignee
    assignees:
      - JoranAngevaare
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
